#!/bin/bash

GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
BOLD='\e[1m'
NC='\033[0m'

IP=`hostname -I | awk '{print $1}'`
printf "                    @@@@@@@@@@@@@@@@@@@\n"
printf "                   @@.               .@@\n"
printf "     %@@@@@@.     @@     @@@@@@@@@     @@\n"
printf "    @@@    @@*   @@.                   .@@\n"
printf "  &@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&\n"
printf "@@@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@@@\n"
printf "@@                                                       @@\n"
printf "@@                     @@@@@@@@@@@@@.        *@@  @@@@@  @@\n"
printf "@@                  @@@@           @@@@                  @@\n"
printf "@@@@@@@@@@@@@@@@@@@@@    #@@@@@@@#    @@@@@@@@@@@@@@@@@@@@@\n"
printf "@@              @@@   @@@@(     (@@@@   @@@              @@\n"
printf "@@             &@@  .@@%           %@@.  @@&             @@\n"
printf "@@             @@   @@               @@   @@             @@\n"
printf "@@            %@@  @@*               /@@  @@%            @@\n"
printf "@@            @@%  @@                 @@  %@@            @@\n"
printf "@@            *@@  @@&               &@@  @@*            @@\n"
printf "@@             @@   @@*             *@@   @@             @@\n"
printf "@@              @@   @@@           @@@   @@              @@\n"
printf "@@%%%%%%%%%%%%%%%@@%   @@@@@&%&@@@@@   %@@%%%%%%%%%%%%%%%@@\n"
printf "@@@@@@@@@@@@@@@@@@@@@@     *&@&*     @@@@@@@@@@@@@@@@@@@@@@\n"
printf "@@                  ,@@@@&       &@@@@,                  @@\n"
printf "@@                      (@@@@@@@@@(                      @@\n"
printf "@@                                                       @@\n"
printf "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n"
printf "\n\n"
printf "\nTo access the photobooth browse to ${BLUE}http://${IP}${NC} from another device on your network."
printf "\n"
printf "\n${BOLD}* Documentation:    ${NC}${GREEN}https://photoboothproject.github.io${NC}"
printf "\n\n"
